name: fform_validator
description: fform_validator is a Flutter package that helps you to validate your form fields (optional).
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
#dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
